//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargeStation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChargeStation()
        {
            this.ChargingPrice = new HashSet<ChargingPrice>();
            this.ChargingRecord = new HashSet<ChargingRecord>();
        }
    
        public long ID { get; set; }
        public string Charge_Name { get; set; }
        public string Charge_Address { get; set; }
        public Nullable<long> Change_Status { get; set; }
        public Nullable<System.Guid> Charging_Pile_ID { get; set; }
        public Nullable<System.Guid> Charging_Gun_ID { get; set; }
    
        public virtual Charging_Gun Charging_Gun { get; set; }
        public virtual ChargingPile ChargingPile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChargingPrice> ChargingPrice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChargingRecord> ChargingRecord { get; set; }
    }
}
