//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargingPrice
    {
        public long id { get; set; }
        public Nullable<long> User_id { get; set; }
        public Nullable<long> ChargePricing_Station_id { get; set; }
        public Nullable<System.Guid> ChargeGun_Menu { get; set; }
        public Nullable<long> Use_Time_id { get; set; }
    
        public virtual ChargeStation ChargeStation { get; set; }
        public virtual Charging_Gun Charging_Gun { get; set; }
        public virtual User User { get; set; }
        public virtual UseTime UseTime { get; set; }
    }
}
