//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zyberion_Taiwan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.ChargingRecord = new HashSet<ChargingRecord>();
        }
    
        public long ID { get; set; }
        public Nullable<long> User_ID { get; set; }
        public string Car_number { get; set; }
        public string Year { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<long> Car_id { get; set; }
        public string National { get; set; }
        public string Color { get; set; }
        public Nullable<System.DateTime> Creat_time { get; set; }
        public string Health { get; set; }
    
        public virtual CarDisplay CarDisplay { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChargingRecord> ChargingRecord { get; set; }
    }
}
