//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zyberion_Taiwan
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarDisplay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarDisplay()
        {
            this.Car = new HashSet<Car>();
        }
    
        public long ID { get; set; }
        public Nullable<long> Brand_id { get; set; }
        public string Display_no { get; set; }
        public string Display_Name { get; set; }
        public string Content { get; set; }
        public string Price { get; set; }
        public string Engine { get; set; }
        public string Mileage_completed { get; set; }
        public string Battery_Capacity { get; set; }
        public string Charging_time { get; set; }
        public string Maximum_speed { get; set; }
        public string C0_100Speed { get; set; }
        public Nullable<int> SeatNumber { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Height { get; set; }
        public string Motor_Power { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Car> Car { get; set; }
        public virtual CarBrand CarBrand { get; set; }
    }
}
