//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zyberion_Taiwan
{
    using System;
    using System.Collections.Generic;
    
    public partial class UseTime
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UseTime()
        {
            this.ChargingPrice = new HashSet<ChargingPrice>();
        }
    
        public long id { get; set; }
        public string Section { get; set; }
        public string Time { get; set; }
        public string Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChargingPrice> ChargingPrice { get; set; }
    }
}
